/*
 * File: Stand Alone Stub.cs
 *
 * The exe generated by this file is used by the editor to generate stand alone exe's. This
 * file works as a small installer. Basically it 
 * 
 * Copyright (c) Binary Phoenix. All rights reserved.
 */

using System;
using System.IO;
using System.Diagnostics;
using System.Threading;
using System.Drawing;
using System.Collections;
using System.Windows.Forms;

namespace BinaryPhoenix.Fusion.StandAloneStub
{

    /// <summary>
    ///     This is the main class of the stand alone sub, its main purpose is to contain our entry point.
    /// </summary>
    public class StandAloneStub
    {

        /// <summary>
        ///     Our entry point ^.^. Where our app starts.
        /// </summary>
        /// <param name="args">Command line arguments.</param>
        public static void Main(string[] args)
        {
            // Create a new loading window.
            Application.EnableVisualStyles();
            LoadingWindow window = new LoadingWindow();
            window.TopMost = true;
            window.Show();
        }

    }

}
